### ISSUE TITLE
pip install of requirements fails in newer versions of pip due to certifi being a disutils project

### ISSUE THREAD

**Issue by KeirSimmons** [ADGEfficiency/energy_py#18]
`certifi` is a disutils project and so newer versions of `pip` cannot uninstall it. A workaround is to ignore already installed requirements which I will propose as a fix/solution, but someone who knows the codebase better than me should be able to tell if this will cause any issues. Is the specific version of `certifi` necessary?

**Comment by ADGEfficiency** [comment]
Hi Keir, thanks for opening the issue - I will setup the requirements.txt from scratch and see if we can get away with a different version.  

All the fun stuff is happening on the dev branch at the moment - I'm right in the middle of a major DQN rebuild :)

**Comment by ADGEfficiency** [comment]
Closing this as the change has been made to master - I also simplified the requirements.txt in the recent sync of dev to master branch
